approvedGitRepositories: []

enableScripts: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.15.0.cjs

# 10080 = 7 days
npmMinimalAgeGate: 10080

npmPreapprovedPackages:
  - '@grafana/*'
