services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
  loki:
    image: grafana/loki:k272-e15c650
    environment:
      LOG_CLUSTER_DEPTH: '8'
      LOG_SIM_TH: '0.3'
    env_file:
      - ./config/.env
    ports:
      - '3100:3100'
    volumes:
      - ./config/loki-config.yaml:/etc/loki/local-config.yaml
      - ./config/loki-overrides.yaml:/etc/loki/overrides.yaml
    command:
      - -config.file=/etc/loki/local-config.yaml
      - -runtime-config.file=/etc/loki/overrides.yaml
    restart: on-failure
