name: Plugins Platform - CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  CI:
    uses: grafana/plugin-ci-workflows/.github/workflows/ci.yml@main
    with:
      # Playwright e2e tests
      run-playwright: false
