name: Plugins Platform - CI

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  CI:
    uses: grafana/plugin-ci-workflows/.github/workflows/ci.yml@main
    with:
      # Playwright e2e tests
      run-playwright-with-skip-grafana-dev-image: true
      run-playwright-with-grafana-dependency: '>=12.2.0'
      upload-playwright-artifacts: true
      playwright-docker-compose-file: docker-compose.yaml
      playwright-grafana-url: http://localhost:3000
