name: Plugins Platform - CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  CI:
    uses: grafana/plugin-ci-workflows/.github/workflows/ci.yml@ci-cd-workflows/v7.2.0
    with:
      playwright-docker-compose-file: docker-compose.ci.yaml
